export const infoCards = [
    [
      {
        word: 'cry',
        translation: 'плакать',
        image: 'img/cry.jpg',
        audioSrc: 'audio/cry.mm3',
      },
      {
        word: 'dance',
        translation: 'танцевать',
        image: 'img/dance.jpg',
        audioSrc: 'audio/dance.mm3',
      },
      {
        word: 'dive',
        translation: 'нырять',
        image: 'img/dive.jpg',
        audioSrc: 'audio/dive.mp3',
      },
      {
        word: 'draw',
        translation: 'рисовать',
        image: 'img/draw.jpg',
        audioSrc: 'audio/draw.mp3',
      },
      {
        word: 'fishing',
        translation: 'ловить рыбу',
        image: 'img/fishing.jpg',
        audioSrc: 'audio/fishing.mp3',
      },
      {
        word: 'fly',
        translation: 'летать',
        image: 'img/fly.jpg',
        audioSrc: 'audio/fly.mp3',
      },
      {
        word: 'hug',
        translation: 'обнимать',
        image: 'img/hug.jpg',
        audioSrc: 'audio/hug.mp3',
      },
      {
        word: 'jump',
        translation: 'прыгать',
        image: 'img/jump.jpg',
        audioSrc: 'audio/jump.mp3',
      },
    ],
    [
      {
        word: 'open',
        translation: 'открывать',
        image: 'img/open.jpg',
        audioSrc: 'audio/open.mp3',
      },
      {
        word: 'play',
        translation: 'играть',
        image: 'img/play.jpg',
        audioSrc: 'audio/play.mp3',
      },
      {
        word: 'point',
        translation: 'указывать',
        image: 'img/point.jpg',
        audioSrc: 'audio/point.mp3',
      },
      {
        word: 'ride',
        translation: 'ездить',
        image: 'img/ride.jpg',
        audioSrc: 'audio/ride.mp3',
      },
      {
        word: 'run',
        translation: 'бегать',
        image: 'img/run.jpg',
        audioSrc: 'audio/run.mp3',
      },
      {
        word: 'sing',
        translation: 'петь',
        image: 'img/sing.jpg',
        audioSrc: 'audio/sing.mp3',
      },
      {
        word: 'skip',
        translation: 'пропускать',
        image: 'img/skip.jpg',
        audioSrc: 'audio/skip.mp3',
      },
      {
        word: 'swim',
        translation: 'плавать',
        image: 'img/swim.jpg',
        audioSrc: 'audio/swim.mp3',
      },
    ],
    [
      {
        word: 'cat',
        translation: 'кот',
        image: 'img/cat.jpg',
        audioSrc: 'audio/cat.mp3',
      },
      {
        word: 'chick',
        translation: 'цыплёнок',
        image: 'img/chick.jpg',
        audioSrc: 'audio/chick.mp3',
      },
      {
        word: 'chicken',
        translation: 'курица',
        image: 'img/chicken.jpg',
        audioSrc: 'audio/chicken.mp3',
      },
      {
        word: 'dog',
        translation: 'собака',
        image: 'img/dog.jpg',
        audioSrc: 'audio/dog.mp3',
      },
      {
        word: 'horse',
        translation: 'лошадь',
        image: 'img/horse.jpg',
        audioSrc: 'audio/horse.mp3',
      },
      {
        word: 'pig',
        translation: 'свинья',
        image: 'img/pig.jpg',
        audioSrc: 'audio/pig.mp3',
      },
      {
        word: 'rabbit',
        translation: 'кролик',
        image: 'img/rabbit.jpg',
        audioSrc: 'audio/rabbit.mp3',
      },
      {
        word: 'sheep',
        translation: 'овца',
        image: 'img/sheep.jpg',
        audioSrc: 'audio/sheep.mp3',
      },
    ],
    [
      {
        word: 'bird',
        translation: 'птица',
        image: 'img/bird.jpg',
        audioSrc: 'audio/bird.mp3',
      },
      {
        word: 'fish',
        translation: 'рыба',
        image: 'img/fish1.jpg',
        audioSrc: 'audio/fish.mm3',
      },
      {
        word: 'frog',
        translation: 'жаба',
        image: 'img/frog.jpg',
        audioSrc: 'audio/frog.mm3',
      },
      {
        word: 'giraffe',
        translation: 'жирафа',
        image: 'img/giraffe.jpg',
        audioSrc: 'audio/giraffe.mm3',
      },
      {
        word: 'lion',
        translation: 'лев',
        image: 'img/lion.jpg',
        audioSrc: 'audio/lion.mm3',
      },
      {
        word: 'mouse',
        translation: 'мышь',
        image: 'img/mouse.jpg',
        audioSrc: 'audio/mouse.mm3',
      },
      {
        word: 'turtle',
        translation: 'черепаха',
        image: 'img/turtle.jpg',
        audioSrc: 'audio/turtle.mm3',
      },
      {
        word: 'dolphin',
        translation: 'дельфин',
        image: 'img/dolphin.jpg',
        audioSrc: 'audio/dolphin.mm3',
      },
    ],
    [
      {
        word: 'skirt',
        translation: 'юбка',
        image: 'img/skirt.jpg',
        audioSrc: 'audio/skirt.mm3',
      },
      {
        word: 'pants',
        translation: 'брюки',
        image: 'img/pants.jpg',
        audioSrc: 'audio/pants.mm3',
      },
      {
        word: 'blouse',
        translation: 'блузка',
        image: 'img/blouse.jpg',
        audioSrc: 'audio/blouse.mm3',
      },
      {
        word: 'dress',
        translation: 'платье',
        image: 'img/dress.jpg',
        audioSrc: 'audio/dress.mm3',
      },
      {
        word: 'boot',
        translation: 'ботинок',
        image: 'img/boot.jpg',
        audioSrc: 'audio/boot.mm3',
      },
      {
        word: 'shirt',
        translation: 'рубашка',
        image: 'img/shirt.jpg',
        audioSrc: 'audio/shirt.mm3',
      },
      {
        word: 'coat',
        translation: 'пальто',
        image: 'img/coat.jpg',
        audioSrc: 'audio/coat.mm3',
      },
      {
        word: 'shoe',
        translation: 'туфли',
        image: 'img/shoe.jpg',
        audioSrc: 'audio/shoe.mm3',
      },
    ],
    [
      {
        word: 'sad',
        translation: 'грустный',
        image: 'img/sad.jpg',
        audioSrc: 'audio/sad.mm3',
      },
      {
        word: 'angry',
        translation: 'сердитый',
        image: 'img/angry.jpg',
        audioSrc: 'audio/angry.mm3',
      },
      {
        word: 'happy',
        translation: 'счастливый',
        image: 'img/happy.jpg',
        audioSrc: 'audio/happy.mm3',
      },
      {
        word: 'tired',
        translation: 'уставший',
        image: 'img/tired.jpg',
        audioSrc: 'audio/tired.mm3',
      },
      {
        word: 'surprised',
        translation: 'удивлённый',
        image: 'img/surprised.jpg',
        audioSrc: 'audio/surprised.mm3',
      },
      {
        word: 'scared',
        translation: 'испуганный',
        image: 'img/scared.jpg',
        audioSrc: 'audio/scared.mm3',
      },
      {
        word: 'smile',
        translation: 'улыбка',
        image: 'img/smile.jpg',
        audioSrc: 'audio/smile.mm3',
      },
      {
        word: 'laugh',
        translation: 'смех',
        image: 'img/laugh.jpg',
        audioSrc: 'audio/laugh.mm3',
      },
    ],
    [
      {
        word: 'vegetables',
        translation: 'овощи',
        image: 'img/vegetables.jpg',
        audioSrc: 'audio/vegetables.mm3',
      },
      {
        word: 'porridge',
        translation: 'каша',
        image: 'img/porridge.jpg',
        audioSrc: 'audio/porridge.mm3',
      },
      {
        word: 'strawberry',
        translation: 'клубника',
        image: 'img/strawberry.jpg',
        audioSrc: 'audio/strawberry.mm3',
      },
      {
        word: 'bread',
        translation: 'хлеб',
        image: 'img/bread.jpg',
        audioSrc: 'audio/bread.mm3',
      },
      {
        word: 'pancakes',
        translation: 'блинчики',
        image: 'img/pancakes.jpg',
        audioSrc: 'audio/pancakes.mm3',
      },
      {
        word: 'eggs',
        translation: 'яйца',
        image: 'img/eggs.jpg',
        audioSrc: 'audio/eggs.mm3',
      },
      {
        word: 'grape',
        translation: 'виноград',
        image: 'img/grape.jpg',
        audioSrc: 'audio/grape.mm3',
      },
      {
        word: 'ice cream',
        translation: 'мороженое',
        image: 'img/ice cream.jpg',
        audioSrc: 'audio/ice cream.mm3',
      },
    ],
    [
      {
        word: 'boat',
        translation: 'лодка',
        image: 'img/boat.jpg',
        audioSrc: 'audio/boat.mm3',
      },
      {
        word: 'water',
        translation: 'вода',
        image: 'img/water.jpg',
        audioSrc: 'audio/water.mm3',
      },
      {
        word: 'beach',
        translation: 'пляж',
        image: 'img/beach.jpg',
        audioSrc: 'audio/beach.mm3',
      },
      {
        word: 'sand',
        translation: 'песок',
        image: 'img/sand.jpg',
        audioSrc: 'audio/sand.mm3',
      },
      {
        word: 'coral',
        translation: 'корал',
        image: 'img/coral.jpg',
        audioSrc: 'audio/coral.mm3',
      },
      {
        word: 'jellyfish',
        translation: 'медуза',
        image: 'img/jellyfish.jpg',
        audioSrc: 'audio/jellyfish.mm3',
      },
      {
        word: 'wave',
        translation: 'волна',
        image: 'img/wave.jpg',
        audioSrc: 'audio/wave.mm3',
      },
      {
        word: 'pier',
        translation: 'пирс',
        image: 'img/pier.jpg',
        audioSrc: 'audio/pier.mm3',
      },
    ],
  ];
